config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/films')
  resources :films
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/star_wars_cache.rb
class StarWarsCache < ApplicationRecord
  validates :path, uniqueness: true
  validates :path, :payload, presence: true
  def self.get(path)
    record = StarWarsCache.find_by(path: path)
    if record
      record.update_payload if record.stale?
      return record
    else
      return StarWarsCache.create(path: path, payload: StarWarsCache.fetch(path))
    end
  end

  def stale?
    return self.updated_at < 3.days.ago
  end

  def update_payload
    return self.update(payload: StarWarsCache.fetch(self.path))
  end

  def self.fetch(path)
    response = HTTParty.get("https://swapi.co/api#{path}", format: :json)
    return JSON.parse(response.body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @response = StarWarsCache.get(request.original_fullpath).payload
  end

  def show
    @response = StarWarsCache.get(request.original_fullpath).payload

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @response = StarWarsCache.get(request.original_fullpath).payload
  end
  
  def show
    @response = StarWarsCache.get("/people/#{params[:id]}").payload

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_entity_number(url)
    return url.split("/").last
  end

  def strip_api_prefix(url)
    return url.gsub("https://swapi.co/api", "")
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/films/_film.html.erb
<div class="box">
  <h4>Title:</h4>
  <h5><%= @response["title"] %></h5>
</div>

<div class="box">
  <h4>Episode Number:</h4>
  <h5><%= @response["episode_id"] %></h5>
</div>
<div class="box">
  <h4><h4>Director:</h4>
  <h5><%= @response["director"] %></h5>
</div>
<div class="box">
  <h4>Opening Crawl:</h4>
  <h5><%= @response["opening_crawl"] %></h5>
</div>
<div class="box">
  <h4>Characters:</h4>
  <% @response["characters"].each do |c| %>
    <div><%= button_to "Character ##{c.split("/").last}", c.gsub("https://swapi.co/api", ""), remote: true, method: :get %></div>
  <% end %>
</div>

app/views/films/index.html.erb
<h1>Films</h1>

<% @response["results"].each do |film| %>
  <h4><%= link_to film["title"], strip_api_prefix(film["url"]), remote: true %></h4>
<% end %>

app/views/films/show.html.erb
<%= render partial: "film" %>

app/views/films/show.js.erb
$("body").empty()
$("body").append("<%= escape_javascript(render 'films/film') %>")
window.history.pushState(null, "", "<%= escape_javascript(request.original_url) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_person.html.erb
<div class="box">
  <h4>Name:</h4>
  <h5><%= @response["name"] %></h5>
</div>

<div class="box">
  <h4>Gender:</h4>
  <h5><%= @response["gender"] %></h5>
</div>
<div class="box">
  <h4><h4>Birth Year:</h4>
  <h5><%= @response["birth_year"] %></h5>
</div>
<div class="box">
  <h4>Eye Color:</h4>
  <h5><%= @response["eye_color"] %></h5>
</div>
<div class="box">
  <h4>Films:</h4>
  <% @response["films"].each do |film_url| %>
    <div><%= button_to "Film ##{get_entity_number(film_url)}", strip_api_prefix(film_url), remote: true, method: :get %></div>
  <% end %>
</div>

app/views/people/index.html.erb
<h1>People</h1>

<% @response["results"].each do |person| %>
  <h4><%= link_to person["name"], strip_api_prefix(person["url"]) %></h4>
<% end %>

app/views/people/show.html.erb
<%= render partial: "person" %>

app/views/people/show.js.erb
$("body").empty()
$("body").append("<%= escape_javascript(render 'people/person') %>")
window.history.pushState(null, "", "<%= escape_javascript(request.original_url) %>")